import type { Metadata } from "next";
import { Sora, Roboto } from "next/font/google";
import "./globals.css";

const sora = Sora({
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-sora",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["400", "500", "700", "900"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clínica Rocha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-full ${sora.className} ${roboto.className}`}>
        {children}
      </body>
    </html>
  );
}
